
import type { Metadata } from "next";
import { Geist, Geist_Mono, Pacifico } from "next/font/google";
import "./globals.css";

const pacifico = Pacifico({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-pacifico',
})

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Readdy Site",
  description: "Generated by Readdy",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              (function() {
                function getInitialTheme() {
                  const storedTheme = localStorage.getItem('theme');
                  if (storedTheme) {
                    return storedTheme;
                  }
                  return 'dark';
                }
                
                const theme = getInitialTheme();
                document.documentElement.classList.toggle('dark', theme === 'dark');
                
                // Apply theme-specific styles to root
                if (theme === 'dark') {
                  document.documentElement.style.setProperty('--bg-primary', '#0a0a0a');
                  document.documentElement.style.setProperty('--bg-secondary', '#0d0d0d');
                  document.documentElement.style.setProperty('--text-primary', '#ffffff');
                  document.documentElement.style.setProperty('--text-secondary', '#d1d5db');
                  document.documentElement.style.setProperty('--accent-purple', '#a855f7');
                  document.documentElement.style.setProperty('--accent-cyan', '#06b6d4');
                  document.documentElement.style.setProperty('--accent-pink', '#ec4899');
                  document.documentElement.style.setProperty('--success-green', '#10b981');
                } else {
                  document.documentElement.style.setProperty('--bg-primary', '#f9fafb');
                  document.documentElement.style.setProperty('--bg-secondary', '#ffffff');
                  document.documentElement.style.setProperty('--text-primary', '#111827');
                  document.documentElement.style.setProperty('--text-secondary', '#6b7280');
                  document.documentElement.style.setProperty('--accent-purple', '#8b5cf6');
                  document.documentElement.style.setProperty('--accent-cyan', '#0891b2');
                  document.documentElement.style.setProperty('--accent-pink', '#db2777');
                  document.documentElement.style.setProperty('--success-green', '#059669');
                }
              })();
            `,
          }}
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${pacifico.variable} antialiased bg-[var(--bg-primary)] text-[var(--text-primary)]`}
      >
        {children}
      </body>
    </html>
  );
}
